package view;

import javafx.application.Application;
import javafx.stage.Stage;

/**
 * This class is the start point of the program, pushes the front-end GUI to a stage + scene
 * generated by ChooseDirectoryScene.DirectoryScene Code based on: src:
 * https://docs.oracle.com/javafx/2/get_started/hello_world.htm
 */
public class Main extends Application {

  /** Main method to initialize the program */
  public static void main(String[] args) {
    launch(args);
  }

  /** @param primaryStage the main JavaFX stage that the program is initialized and run on */
  public void start(Stage primaryStage) {
    ChooseDirectoryScene chooseDirectory = new ChooseDirectoryScene();
    chooseDirectory.DirectoryScene(primaryStage, ChooseDirectoryScene.selectedDirFile);
  }
}
